### ISSUE TITLE
yarn docs:dev & yarn docs:build

### ISSUE THREAD

**Issue by andresousadotpt** [Novout/cpp4noobs#7]
Boa noite! Estou tendo um problema ao tentar correr "yarn docs:dev" ja fiz yarn install ja fiz tudo e nao funciona... Tem como vocês me ajudarem?

**Comment by Novout** [comment]
Você pode usar os comandos `yarn dev` ou `yarn build` ao invés desses.

Se você apenas quer ler pelo site, pode usar o github pages: https://novout.github.io/cpp4noobs/

Qualquer dúvida pode perguntar por aqui :)

**Comment by andresousadotpt** [comment]
Ah tem site? Ok ok prefiro pelo github pages então ahahah! Obrigado pela ajuda e desculpa a demora da resposta! ahahah
